name: Deploy .NET App to Azure VM (Windows)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Application
      run: dotnet build --configuration Release --no-restore

    - name: Publish Application
      run: dotnet publish --configuration Release --output ./publish

    - name: Deploy to IIS
      shell: powershell
      run: |
        Import-Module WebAdministration
        
        # 1. Stop App Pool to unlock production files
        Stop-WebAppPool -Name "TestingCiCd"
        
        # 2. Deploy files to target folder
        Copy-Item -Path "./publish/*" -Destination "C:\inetpub\wwwroot\TestingCiCd" -Recurse -Force
        
        # 3. Start App Pool back up
        Start-WebAppPool -Name "TestingCiCd"